version: "3.7"

volumes:
  <%= appname %>-nodemodules:
    external: true

services:

  dev:
    image: node:10
    container_name: dev-<%= appname %>
    volumes:
      - <%= appname %>-nodemodules:/usr/work/node_modules
      - .:/usr/work
    environment:
      - NODE_ENV=development
    working_dir: /usr/work
    command: npm run build:watch
